import {
  Target,
  Gem,
  Cog,
  Shield,
  Search,
  Brain,
  Scale,
  Map,
  ClipboardList,
  Pencil,
  Clock,
  FlaskConical,
  BookOpen,
  MessageSquare,
  Lock,
  ArrowLeft,
  Settings,
  FolderOpen,
  Calendar,
  User,
  Power,
  Megaphone,
  Smartphone,
  Factory,
  CheckCircle,
  XCircle,
  Bot,
  Rocket,
  FileEdit,
  BarChart3,
  DollarSign,
  FileText,
  Clipboard,
} from 'lucide-react';
import React from 'react';

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  Target,
  Gem,
  Cog,
  Shield,
  Search,
  Brain,
  Scale,
  Map,
  ClipboardList,
  Pencil,
  Clock,
  FlaskConical,
  BookOpen,
  MessageSquare,
  Lock,
  ArrowLeft,
  Settings,
  FolderOpen,
  Calendar,
  User,
  Power,
  Megaphone,
  Smartphone,
  Factory,
  CheckCircle,
  XCircle,
  Bot,
  Rocket,
  FileEdit,
  BarChart3,
  DollarSign,
  FileText,
  Clipboard,
};

export function ModuleIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name];
  if (!Icon) return <span>{name}</span>;
  return <Icon className={className || 'w-4 h-4'} />;
}
